### ISSUE TITLE
Mint ARK Identifiers

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/cedar#1]
Add ability to mint an ARK identifier via the [Greens](https://github.com/uhlibraries-digital/greens) API, ensuring that multiple ARKs cannot be minted for the same term.

**Comment by seanlw** [comment]
See #2 for ERC information

**Comment by seanlw** [comment]
Should the arks be minted before a concept gets published?

**Comment by seanlw** [comment]
Having the ARK minted before the initial concept is published could leave the ARK as being orphaned if the concept is deleted.
