### ISSUE TITLE
ERC 'what' Update

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/cedar#11]
Does Cedar automatically update the ERC 'what' statement in Greens when a prefLabel is edited?

**Comment by seanlw** [comment]
Yes it should, does it not?

Sean Watkins
Lead Repository Developer
Web Services, University Libraries
University of Houston
A Carnegie-designated Tier One public research university
713-743-0718tel:713-743-0718
slwatkins@uh.edumailto:slwatkins@uh.edu

On Jul 1, 2016, at 3:36 PM, Andy Weidner <notifications@github.com<mailto:notifications@github.com>> wrote:

Does Cedar automatically update the ERC 'what' statement in Greens when a prefLabel is edited?

**Comment by seanlw** [comment]
After some testing, it looks like iQvoc does not change the origin even after the prefLabel is changed. Therefor the URL will not change. If you want both the URL and the prefLabel to change, you will need to expire the concept and create a new one. This looks to be by design in iQvoc.

**Comment by seanlw** [comment]
@metaweidner do you see the need to having this issue open? It has been tested and confirmed unless you have new findings and you can re-open this issue.

**Comment by metaweidner** [comment]
Thank you @seanlw. We'll reopen if we find any problems.
