### ISSUE TITLE
As a developer I would like to have added API support to pull out additional data

### ISSUE THREAD

**Issue by seanlw** [uhlibraries-digital/cedar#13]
IQvoc's API is very limited and as more applications start you use Cedar as a datasource, we need to come up with a better API.

This came during feature requests in Brays: https://github.com/uhlibraries-digital/brays/issues/14

**Comment by seanlw** [comment]
From @metaweidner "The Cedar API enhancements could possibly take the form of a Linked Data Fragments interface."

**Comment by metaweidner** [comment]
**Client & Server LDF libraries**
http://linkeddatafragments.org/software/

**Comment by metaweidner** [comment]
@seanlw The Hydra Applied Linked Data Working Group is actively discussing serving locally hosted vocabularies as Linked Data Fragments https://wiki.duraspace.org/display/hydra/Applied+Linked+Data+Working+Group

**Comment by metaweidner** [comment]
Transferred to Trello.
