### ISSUE TITLE
Update ARK ERC Information

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/cedar#2]
Add ability to update the ERC information for a term's ARK identifier via the [Greens](https://github.com/uhlibraries-digital/greens) API, possibly automatically after an edit.

**Comment by seanlw** [comment]
What if a term gets removed, will the ARK need to be destroyed?

**Comment by metaweidner** [comment]
We should leave the ARK and figure out how to manage expired IDs, recording it as expired in the ERC, and possibly adding a UI filter for active and expired ARKs.

**Comment by seanlw** [comment]
What will be the mapping from the concept to ERC. I need the who, what, when, where

**Comment by metaweidner** [comment]
**who:** University of Houston Libraries Vocabularies
**what:** [skos:prefLabel for concept]
**when:** [date created YYYY-MM-DD]
**where:** [cedar url for concept]

only "what" and "where" should ever need to be updated
maybe the what can be updated automatically if the skos:prefLabel has changed during editing
the where will probably only change if we move to a different vocabulary publishing platform

**Comment by seanlw** [comment]
Should the ark be updated before changes to the concept gets published?

**Comment by seanlw** [comment]
Since the concept changes are not public before published, the ERC should only reflect what is public. i.e. the ERC should only be updated when the new concept version is published.
