### ISSUE TITLE
As a metadata editor I would like to be able to use Cedar as a reconciliation service with Open Refine

### ISSUE THREAD

**Issue by amgaynor** [uhlibraries-digital/cedar#22]
As a metadata editor I would like to be able to use Cedar as a reconciliation service with Open Refine so I can align legacy data with our preferred vocabulary terms more easily during our prep migration.

**Comment by amgaynor** [comment]
@seanlw Let me know if this needs to be abstracted further, i.e. not mention Open Refine, to make it a better story.

**Comment by seanlw** [comment]
@amgaynor I think that's fine. What other reconciliation services are there besides Open Refine?

**Comment by metaweidner** [comment]
Transferred to Trello.
