### ISSUE TITLE
Logo expands when search term entered

### ISSUE THREAD

**Issue by metaweidner** [uhlibraries-digital/cedar#7]
The UH Libraries Vocabularies logo expands when a search term is entered on wide screens.
![screenshot from 2016-04-29 15 36 42](https://cloud.githubusercontent.com/assets/7347746/14928930/79ce10e6-0e20-11e6-8429-0aee3474ae7d.png)

**Comment by metaweidner** [comment]
![cedar_splashimageexpands](https://cloud.githubusercontent.com/assets/7347746/16321494/c6d5194e-3962-11e6-80c1-d0b72e7e2bbd.JPG)

**Comment by seanlw** [comment]
Just need to run 'rake assets:precompile' on the production server to use the correct css.
